version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    target-branch: dev
    open-pull-requests-limit: 10
    groups:
      storybook:
        patterns:
          - "@storybook/*"
          - "@chromatic-com/*"
          - storybook*
      testing:
        patterns:
          - "@testing-library/*"
          - "@vitest/*"
          - vitest
          - jsdom
          - playwright
      linting:
        patterns:
          - eslint*
          - prettier
          - typescript-eslint
      tailwind:
        patterns:
          - tailwindcss
          - "@tailwindcss/*"
